### PR TITLE
Add ico support (for favicon mainly)

### PR DESCRIPTION
**Pull request by Swannbm**
Hello,

I've added support for favicon in template: {% sri_static "favicon.ico" %}.

On a side note, I couldn't manage to get the test running on my laptop (error: pytest-django could not find a Django project (no manage.py file could be found)...) but I am quite new at doing unit test. If you could give a bit more directions on how to contribute, it would be welcome :)

If this PR needs changes, let me know.
Swann

### CODE REVIEW

**Review by RealOrangeOne — COMMENTED** [review]
This looks really good - thanks! Question: Where does your fixture icon come from? Don't want to be committing things without proper attribution / license!

**Comment by Swannbm** [comment]
Ohhh... good point. It was made in a favicon builder website: https://gauger.io/fonticon/
There is seldom information on licence directly on the website, but in the github repository the LICENCE file point to MIT Licence, so I think we are good to go.

**Comment by RealOrangeOne** [comment]
Because the content of the file doesn't matter too much (it doesn't need to be an actual `.ico` file), I'd suggest just replacing it with an empty file and using that as the test fixture.

**Comment by RealOrangeOne** [comment]
This may no longer be necessary now #69 has merged.

**Pull request closed without merging**
